using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using LitJson;
using VeryFS.UnityMCP.Editor.Commands.AgentSkill;
using VeryFS.UnityMCP.Editor.Infrastructure;

namespace VeryFS.UnityMCP.Editor.UI
{
    internal enum AgentClientConfigStatus
    {
        Off,
        Current,
        Stale,
        Missing,
        Invalid
    }

    internal enum AgentClientSkillStatus
    {
        Off,
        Installed,
        Missing,
        Custom
    }

    internal sealed class AgentClientStatus
    {
        public AgentClientStatus(
            string client,
            bool enabled,
            AgentClientConfigStatus configStatus,
            AgentClientSkillStatus skillStatus,
            string configPath,
            string skillPath)
        {
            Client = client;
            Enabled = enabled;
            ConfigStatus = configStatus;
            SkillStatus = skillStatus;
            ConfigPath = configPath;
            SkillPath = skillPath;
        }

        public string Client { get; }
        public bool Enabled { get; }
        public AgentClientConfigStatus ConfigStatus { get; }
        public AgentClientSkillStatus SkillStatus { get; }
        public string ConfigPath { get; }
        public string SkillPath { get; }
    }

    internal sealed class AgentClientIntegrationSnapshot
    {
        public AgentClientIntegrationSnapshot(McpClientTarget enabledTargets, IReadOnlyList<AgentClientStatus> clients)
        {
            EnabledTargets = enabledTargets;
            Clients = clients;
        }

        public McpClientTarget EnabledTargets { get; }
        public IReadOnlyList<AgentClientStatus> Clients { get; }

        public IReadOnlyList<string> EnabledCustomSkillPaths()
        {
            var paths = new List<string>();
            foreach (AgentClientStatus client in Clients)
            {
                if (client.Enabled && client.SkillStatus == AgentClientSkillStatus.Custom &&
                    !paths.Contains(client.SkillPath))
                {
                    paths.Add(client.SkillPath);
                }
            }
            return paths;
        }
    }

    internal sealed class AgentClientActionResult
    {
        public AgentClientActionResult(bool succeeded, string message)
        {
            Succeeded = succeeded;
            Message = message;
        }

        public bool Succeeded { get; }
        public string Message { get; }
    }

    internal sealed class ServerMonitorIntegrationController
    {
        private const string SkillName = "unitymcp";
        private const string GeneratedMarker =
            "Generated by `install-agent-skill` from the bundled UnityMCP skill template";

        private readonly string projectRoot;
        private readonly Func<DiscoveryDocument> discoveryProvider;
        private readonly IAgentSkillFileStore fileStore;
        private readonly Func<IReadOnlyList<string>, bool, string> installer;

        public ServerMonitorIntegrationController(
            string projectRoot,
            Func<DiscoveryDocument> discoveryProvider,
            IAgentSkillFileStore fileStore,
            Func<IReadOnlyList<string>, bool, string> installer)
        {
            this.projectRoot = projectRoot;
            this.discoveryProvider = discoveryProvider;
            this.fileStore = fileStore;
            this.installer = installer;
        }

        public McpClientTarget LoadTargets()
        {
            return McpClientIntegrationPreferences.Load(projectRoot);
        }

        public AgentClientIntegrationSnapshot ReadStatuses()
        {
            McpClientTarget enabled = LoadTargets();
            DiscoveryDocument doc = discoveryProvider();
            var clients = new List<AgentClientStatus>
            {
                StatusFor(McpClientTargets.Claude, enabled, doc),
                StatusFor(McpClientTargets.Codex, enabled, doc),
                StatusFor(McpClientTargets.OpenCode, enabled, doc)
            };
            return new AgentClientIntegrationSnapshot(enabled, clients);
        }

        public AgentClientActionResult ApplyTargets(McpClientTarget nextTargets)
        {
            McpClientTarget currentTargets = LoadTargets();
            AgentClientIntegrationSnapshot snapshot = ReadStatuses();
            foreach (AgentClientStatus status in snapshot.Clients)
            {
                if (status.ConfigStatus != AgentClientConfigStatus.Invalid)
                {
                    continue;
                }

                McpClientTarget target = TargetFor(status.Client);
                if ((currentTargets & target) != (nextTargets & target))
                {
                    return new AgentClientActionResult(
                        false,
                        "Config for " + status.Client + " is invalid: " + status.ConfigPath);
                }
            }

            try
            {
                DiscoveryFileWriter.Write(projectRoot, discoveryProvider(), nextTargets);

                IReadOnlyList<string> deleteClients = DisabledSkillClients(currentTargets, nextTargets);
                if (deleteClients.Count > 0)
                {
                    fileStore.DeleteGenerated(projectRoot, SkillName, deleteClients);
                }

                McpClientIntegrationPreferences.Save(projectRoot, nextTargets);
                return new AgentClientActionResult(true, "Agent client settings updated.");
            }
            catch (Exception exception)
            {
                return new AgentClientActionResult(false, exception.Message);
            }
        }

        public AgentClientActionResult InstallEnabledSkills(bool allowOverwriteCustom)
        {
            AgentClientIntegrationSnapshot snapshot = ReadStatuses();
            IReadOnlyList<string> clients = McpClientTargets.ToNames(snapshot.EnabledTargets);
            if (clients.Count == 0)
            {
                return new AgentClientActionResult(false, "No agent client is enabled.");
            }

            IReadOnlyList<string> customPaths = snapshot.EnabledCustomSkillPaths();
            if (customPaths.Count > 0 && !allowOverwriteCustom)
            {
                return new AgentClientActionResult(false, "Custom skill confirmation required.");
            }

            try
            {
                string message = installer(clients, true);
                return new AgentClientActionResult(true, message);
            }
            catch (Exception exception)
            {
                return new AgentClientActionResult(false, exception.Message);
            }
        }

        private AgentClientStatus StatusFor(string client, McpClientTarget enabledTargets, DiscoveryDocument doc)
        {
            bool enabled = (enabledTargets & TargetFor(client)) != 0;
            if (!enabled)
            {
                return new AgentClientStatus(
                    client,
                    false,
                    AgentClientConfigStatus.Off,
                    AgentClientSkillStatus.Off,
                    ConfigPathFor(client),
                    SkillPathFor(client));
            }

            return new AgentClientStatus(
                client,
                true,
                ConfigStatusFor(client, doc),
                SkillStatusFor(client),
                ConfigPathFor(client),
                SkillPathFor(client));
        }

        private AgentClientConfigStatus ConfigStatusFor(string client, DiscoveryDocument doc)
        {
            if (client == McpClientTargets.Claude)
            {
                return JsonMcpStatus(
                    Path.Combine(projectRoot, DiscoveryFileWriter.McpConfigFileName),
                    "mcpServers",
                    doc,
                    false);
            }
            if (client == McpClientTargets.OpenCode)
            {
                return JsonMcpStatus(
                    Path.Combine(projectRoot, DiscoveryFileWriter.OpenCodeConfigDirectoryName,
                        DiscoveryFileWriter.OpenCodeConfigFileName),
                    "mcp",
                    doc,
                    true);
            }

            return CodexStatus(doc);
        }

        private AgentClientConfigStatus JsonMcpStatus(
            string path,
            string containerKey,
            DiscoveryDocument doc,
            bool requireEnabled)
        {
            if (!File.Exists(path))
            {
                return AgentClientConfigStatus.Missing;
            }

            JsonData root;
            try
            {
                root = JsonMapper.ToObject(File.ReadAllText(path));
            }
            catch (Exception)
            {
                return AgentClientConfigStatus.Invalid;
            }

            if (root == null || !root.IsObject)
            {
                return AgentClientConfigStatus.Invalid;
            }

            if (!root.ContainsKey(containerKey))
            {
                return AgentClientConfigStatus.Missing;
            }

            if (root[containerKey] == null || !root[containerKey].IsObject)
            {
                return AgentClientConfigStatus.Invalid;
            }

            JsonData servers = root[containerKey];
            if (!servers.ContainsKey(DiscoveryFileWriter.McpServerName))
            {
                return AgentClientConfigStatus.Missing;
            }

            JsonData server = servers[DiscoveryFileWriter.McpServerName];
            if (server == null || !server.IsObject)
            {
                return AgentClientConfigStatus.Invalid;
            }

            if (!HasString(server, "url", doc.ServerUrl) ||
                !server.ContainsKey("headers") ||
                server["headers"] == null ||
                !server["headers"].IsObject ||
                !HasString(server["headers"], "Authorization", "Bearer " + doc.ClientToken))
            {
                return AgentClientConfigStatus.Stale;
            }

            if (requireEnabled && (!server.ContainsKey("enabled") || !server["enabled"].IsBoolean ||
                    !(bool)server["enabled"]))
            {
                return AgentClientConfigStatus.Stale;
            }

            return AgentClientConfigStatus.Current;
        }

        private AgentClientConfigStatus CodexStatus(DiscoveryDocument doc)
        {
            string path = Path.Combine(projectRoot, DiscoveryFileWriter.CodexConfigDirectoryName,
                DiscoveryFileWriter.CodexConfigFileName);
            if (!File.Exists(path))
            {
                return AgentClientConfigStatus.Missing;
            }

            string text;
            try
            {
                text = File.ReadAllText(path);
            }
            catch (Exception)
            {
                return AgentClientConfigStatus.Invalid;
            }

            string header = "[mcp_servers." + DiscoveryFileWriter.McpServerName + "]";
            if (!text.Contains(header))
            {
                return AgentClientConfigStatus.Missing;
            }

            bool current = text.Contains("url = " + TomlString(doc.ServerUrl)) &&
                text.Contains("http_headers = { Authorization = " + TomlString("Bearer " + doc.ClientToken) + " }");
            return current ? AgentClientConfigStatus.Current : AgentClientConfigStatus.Stale;
        }

        private AgentClientSkillStatus SkillStatusFor(string client)
        {
            string path = SkillPathFor(client);
            if (!File.Exists(path))
            {
                return AgentClientSkillStatus.Missing;
            }

            string content = File.ReadAllText(path);
            return content.Contains(GeneratedMarker)
                ? AgentClientSkillStatus.Installed
                : AgentClientSkillStatus.Custom;
        }

        private string ConfigPathFor(string client)
        {
            if (client == McpClientTargets.Claude)
            {
                return Path.Combine(projectRoot, DiscoveryFileWriter.McpConfigFileName);
            }
            if (client == McpClientTargets.OpenCode)
            {
                return Path.Combine(projectRoot, DiscoveryFileWriter.OpenCodeConfigDirectoryName,
                    DiscoveryFileWriter.OpenCodeConfigFileName);
            }

            return Path.Combine(projectRoot, DiscoveryFileWriter.CodexConfigDirectoryName,
                DiscoveryFileWriter.CodexConfigFileName);
        }

        private string SkillPathFor(string client)
        {
            if (client == McpClientTargets.OpenCode)
            {
                return Path.Combine(projectRoot, ".opencode", "skills", SkillName, "SKILL.md");
            }

            return Path.Combine(projectRoot, ".agents", "skills", SkillName, "SKILL.md");
        }

        private static bool HasString(JsonData data, string key, string expected)
        {
            return data.ContainsKey(key) && data[key] != null && data[key].IsString &&
                string.Equals((string)data[key], expected, StringComparison.Ordinal);
        }

        private static McpClientTarget TargetFor(string client)
        {
            if (client == McpClientTargets.Claude)
            {
                return McpClientTarget.Claude;
            }
            if (client == McpClientTargets.Codex)
            {
                return McpClientTarget.Codex;
            }
            return McpClientTarget.OpenCode;
        }

        private static IReadOnlyList<string> DisabledSkillClients(McpClientTarget currentTargets, McpClientTarget nextTargets)
        {
            var clients = new List<string>();
            bool hadAgents = (currentTargets & (McpClientTarget.Claude | McpClientTarget.Codex)) != 0;
            bool hasAgents = (nextTargets & (McpClientTarget.Claude | McpClientTarget.Codex)) != 0;
            if (hadAgents && !hasAgents)
            {
                clients.Add(McpClientTargets.Claude);
            }
            if ((currentTargets & McpClientTarget.OpenCode) != 0 &&
                (nextTargets & McpClientTarget.OpenCode) == 0)
            {
                clients.Add(McpClientTargets.OpenCode);
            }
            return clients;
        }

        private static string TomlString(string value)
        {
            var builder = new StringBuilder();
            builder.Append('"');
            foreach (char c in value ?? string.Empty)
            {
                if (c == '\\')
                {
                    builder.Append("\\\\");
                }
                else if (c == '"')
                {
                    builder.Append("\\\"");
                }
                else
                {
                    builder.Append(c);
                }
            }
            builder.Append('"');
            return builder.ToString();
        }
    }
}
