using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using LitJson;

namespace VeryFS.UnityMCP.Editor.Infrastructure
{
    /// <summary>
    /// Writes the project-root UnityMCP.json discovery file that MCP clients read
    /// to find the server URL + client token. The shape is fixed by the RPC design
    /// (§10). On unix the file is chmod 0600 (owner-only) because it carries a
    /// secret; the unity token is never included.
    /// </summary>
    public static class DiscoveryFileWriter
    {
        public const string FileName = "UnityMCP.json";
        public const string McpConfigFileName = ".mcp.json";
        public const string CodexConfigDirectoryName = ".codex";
        public const string CodexConfigFileName = "config.toml";
        public const string McpServerName = "very-unity-mcp";
        public const int ProtocolVersion = 1;
        private const string LegacyMcpServerName = "unity-mcp";
        private const string CodexManagedBlockStart = "# <very-unity-mcp-codex-config>";
        private const string CodexManagedBlockEnd = "# </very-unity-mcp-codex-config>";
        private const string LegacyCodexManagedBlockStart = "# <unity-mcp-codex-config>";
        private const string LegacyCodexManagedBlockEnd = "# </unity-mcp-codex-config>";
        private const string CodexGeneratedComment = "# Auto-generated by Unity MCP. This file contains a bearer token.";
        private const string CodexRegeneratedComment = "# It is regenerated on Unity startup and should stay git-ignored.";

        /// <summary>
        /// Writes doc to &lt;projectRoot&gt;/UnityMCP.json, &lt;projectRoot&gt;/.mcp.json,
        /// and &lt;projectRoot&gt;/.codex/config.toml; returns the UnityMCP.json path.
        /// .mcp.json lets Claude Code (and compatible MCP clients) discover the server
        /// automatically, while .codex/config.toml gives Codex the same project-local MCP
        /// setup. Generated client config files are git-ignored and regenerated each time
        /// so the client token stays in sync.
        /// </summary>
        public static string Write(string projectRoot, DiscoveryDocument doc)
        {
            if (string.IsNullOrEmpty(projectRoot))
            {
                throw new ArgumentException("Project root cannot be null or empty.", nameof(projectRoot));
            }

            if (doc == null)
            {
                throw new ArgumentNullException(nameof(doc));
            }

            var server = new JsonData();
            server["pid"] = doc.ServerPid;
            server["port"] = doc.Port;
            server["url"] = doc.ServerUrl;
            server["token"] = doc.ClientToken;

            var root = new JsonData();
            root["protocolVersion"] = ProtocolVersion;
            root["projectPath"] = doc.ProjectPath;
            root["editorPid"] = doc.EditorPid;
            root["editorSessionId"] = doc.EditorSessionId;
            root["server"] = server;

            var path = Path.Combine(projectRoot, FileName);
            File.WriteAllText(path, root.ToJson());
            RestrictToOwner(path);

            WriteMcpConfig(projectRoot, doc.ServerUrl, doc.ClientToken);
            WriteCodexConfig(projectRoot, doc.ServerUrl, doc.ClientToken);

            return path;
        }

        private static void WriteMcpConfig(string projectRoot, string serverUrl, string clientToken)
        {
            var headers = new JsonData();
            headers["Authorization"] = "Bearer " + clientToken;

            var serverEntry = new JsonData();
            serverEntry["type"] = "http";
            serverEntry["url"] = serverUrl;
            serverEntry["headers"] = headers;

            var servers = new JsonData();
            servers[McpServerName] = serverEntry;

            var config = new JsonData();
            config["mcpServers"] = servers;

            var mcpPath = Path.Combine(projectRoot, McpConfigFileName);
            File.WriteAllText(mcpPath, config.ToJson());
        }

        private static void WriteCodexConfig(string projectRoot, string serverUrl, string clientToken)
        {
            var codexDir = Path.Combine(projectRoot, CodexConfigDirectoryName);
            Directory.CreateDirectory(codexDir);

            var codexPath = Path.Combine(codexDir, CodexConfigFileName);
            var existing = File.Exists(codexPath) ? File.ReadAllText(codexPath) : string.Empty;
            var withoutUnityMcp = RemoveUnityMcpConfig(existing).TrimEnd();

            var builder = new StringBuilder();
            if (!string.IsNullOrEmpty(withoutUnityMcp))
            {
                builder.Append(withoutUnityMcp);
                builder.AppendLine();
                builder.AppendLine();
            }

            builder.AppendLine(CodexManagedBlockStart);
            builder.AppendLine(CodexGeneratedComment);
            builder.AppendLine(CodexRegeneratedComment);
            builder.Append("[mcp_servers.");
            builder.Append(McpServerName);
            builder.AppendLine("]");
            builder.Append("url = ");
            builder.AppendLine(TomlString(serverUrl));
            builder.Append("http_headers = { Authorization = ");
            builder.Append(TomlString("Bearer " + clientToken));
            builder.AppendLine(" }");
            builder.AppendLine(CodexManagedBlockEnd);

            File.WriteAllText(codexPath, builder.ToString());
        }

        private static string RemoveUnityMcpConfig(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return string.Empty;
            }

            var lines = text.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
            var builder = new StringBuilder();
            var skipping = false;
            var skippingManagedBlock = false;

            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                if (trimmed == CodexManagedBlockStart || trimmed == LegacyCodexManagedBlockStart)
                {
                    skippingManagedBlock = true;
                    continue;
                }

                if (skippingManagedBlock)
                {
                    if (trimmed == CodexManagedBlockEnd || trimmed == LegacyCodexManagedBlockEnd)
                    {
                        skippingManagedBlock = false;
                    }
                    continue;
                }

                if (trimmed == CodexGeneratedComment || trimmed == CodexRegeneratedComment)
                {
                    continue;
                }

                if (IsUnityMcpHeader(trimmed))
                {
                    skipping = true;
                    continue;
                }

                if (skipping && IsTableHeader(trimmed) && !IsUnityMcpHeader(trimmed))
                {
                    skipping = false;
                }

                if (!skipping)
                {
                    builder.AppendLine(line);
                }
            }

            return builder.ToString();
        }

        private static bool IsUnityMcpHeader(string trimmedLine)
        {
            return IsMcpServerHeader(trimmedLine, McpServerName)
                || IsMcpServerHeader(trimmedLine, LegacyMcpServerName);
        }

        private static bool IsMcpServerHeader(string trimmedLine, string serverName)
        {
            return trimmedLine == "[mcp_servers." + serverName + "]"
                || trimmedLine.StartsWith("[mcp_servers." + serverName + ".", StringComparison.Ordinal);
        }

        private static bool IsTableHeader(string trimmedLine)
        {
            return trimmedLine.StartsWith("[", StringComparison.Ordinal)
                && trimmedLine.EndsWith("]", StringComparison.Ordinal);
        }

        private static string TomlString(string value)
        {
            var builder = new StringBuilder();
            builder.Append('"');
            foreach (var c in value ?? string.Empty)
            {
                switch (c)
                {
                    case '\\':
                        builder.Append("\\\\");
                        break;
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\b':
                        builder.Append("\\b");
                        break;
                    case '\t':
                        builder.Append("\\t");
                        break;
                    case '\n':
                        builder.Append("\\n");
                        break;
                    case '\f':
                        builder.Append("\\f");
                        break;
                    case '\r':
                        builder.Append("\\r");
                        break;
                    default:
                        if (char.IsControl(c))
                        {
                            builder.Append("\\u");
                            builder.Append(((int)c).ToString("x4"));
                        }
                        else
                        {
                            builder.Append(c);
                        }
                        break;
                }
            }
            builder.Append('"');
            return builder.ToString();
        }

        // chmod 0600 on unix. gorilla-style FileMode is not honored by Mono's
        // File API here, so we shell out to chmod; on Windows this is a no-op.
        private static void RestrictToOwner(string path)
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                return;
            }

            var psi = new System.Diagnostics.ProcessStartInfo("chmod", "600 \"" + path + "\"")
            {
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using (var proc = System.Diagnostics.Process.Start(psi))
            {
                proc.WaitForExit();
                if (proc.ExitCode != 0)
                {
                    throw new System.IO.IOException(
                        "chmod 600 failed on " + path + " (exit " + proc.ExitCode +
                        "); discovery file may be world-readable");
                }
            }
        }
    }
}
