using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using LitJson;

namespace VeryFS.UnityMCP.Editor.Infrastructure
{
    /// <summary>
    /// Writes the project-root UnityMCP.json discovery file that MCP clients read
    /// to find the server URL + client token. The shape is fixed by the RPC design
    /// (§10). On unix the file is chmod 0600 (owner-only) because it carries a
    /// secret; the unity token is never included.
    /// </summary>
    public static class DiscoveryFileWriter
    {
        public const string FileName = "UnityMCP.json";
        public const string McpConfigFileName = ".mcp.json";
        public const string CodexConfigDirectoryName = ".codex";
        public const string CodexConfigFileName = "config.toml";
        public const string OpenCodeConfigDirectoryName = ".opencode";
        public const string OpenCodeConfigFileName = "opencode.json";
        public const string McpServerName = "very-unity-mcp";
        public const int ProtocolVersion = 1;
        private const string LegacyMcpServerName = "unity-mcp";
        private const string OpenCodeSchema = "https://opencode.ai/config.json";
        private const string CodexManagedBlockStart = "# <very-unity-mcp-codex-config>";
        private const string CodexManagedBlockEnd = "# </very-unity-mcp-codex-config>";
        private const string LegacyCodexManagedBlockStart = "# <unity-mcp-codex-config>";
        private const string LegacyCodexManagedBlockEnd = "# </unity-mcp-codex-config>";
        private const string CodexGeneratedComment = "# Auto-generated by Unity MCP. This file contains a bearer token.";
        private const string CodexRegeneratedComment = "# It is regenerated on Unity startup and should stay git-ignored.";

        /// <summary>
        /// Writes doc to &lt;projectRoot&gt;/UnityMCP.json, &lt;projectRoot&gt;/.mcp.json,
        /// and &lt;projectRoot&gt;/.codex/config.toml; returns the UnityMCP.json path.
        /// .mcp.json lets Claude Code (and compatible MCP clients) discover the server
        /// automatically, while .codex/config.toml gives Codex the same project-local MCP
        /// setup. Generated client config files are git-ignored and regenerated each time
        /// so the client token stays in sync.
        /// </summary>
        public static string Write(string projectRoot, DiscoveryDocument doc)
        {
            return Write(projectRoot, doc, McpClientTarget.All);
        }

        public static string Write(string projectRoot, DiscoveryDocument doc, McpClientTarget targets)
        {
            if (string.IsNullOrEmpty(projectRoot))
            {
                throw new ArgumentException("Project root cannot be null or empty.", nameof(projectRoot));
            }

            if (doc == null)
            {
                throw new ArgumentNullException(nameof(doc));
            }

            var server = new JsonData();
            server["pid"] = doc.ServerPid;
            server["port"] = doc.Port;
            server["url"] = doc.ServerUrl;
            server["token"] = doc.ClientToken;

            var root = new JsonData();
            root["protocolVersion"] = ProtocolVersion;
            root["projectPath"] = doc.ProjectPath;
            root["editorPid"] = doc.EditorPid;
            root["editorSessionId"] = doc.EditorSessionId;
            root["server"] = server;

            var path = Path.Combine(projectRoot, FileName);
            File.WriteAllText(path, root.ToJson());
            RestrictToOwner(path);

            if ((targets & McpClientTarget.Claude) != 0)
            {
                WriteMcpConfig(projectRoot, doc.ServerUrl, doc.ClientToken);
            }
            else
            {
                RemoveMcpConfig(projectRoot);
            }

            if ((targets & McpClientTarget.Codex) != 0)
            {
                WriteCodexConfig(projectRoot, doc.ServerUrl, doc.ClientToken);
            }
            else
            {
                RemoveCodexConfig(projectRoot);
            }

            if ((targets & McpClientTarget.OpenCode) != 0)
            {
                WriteOpenCodeConfig(projectRoot, doc.ServerUrl, doc.ClientToken);
            }
            else
            {
                RemoveOpenCodeConfig(projectRoot);
            }

            return path;
        }

        private static void WriteMcpConfig(string projectRoot, string serverUrl, string clientToken)
        {
            var mcpPath = Path.Combine(projectRoot, McpConfigFileName);
            JsonData config = ReadJsonObjectOrNew(mcpPath);
            if (config == null)
            {
                return;
            }

            JsonData servers = EnsureObject(config, "mcpServers");
            RemoveUnityMcpJsonEntries(servers);
            servers[McpServerName] = McpServerEntry(serverUrl, clientToken);

            File.WriteAllText(mcpPath, config.ToJson());
        }

        private static void RemoveMcpConfig(string projectRoot)
        {
            var mcpPath = Path.Combine(projectRoot, McpConfigFileName);
            if (!File.Exists(mcpPath))
            {
                return;
            }

            JsonData config = ReadJsonObjectOrNew(mcpPath);
            if (config == null)
            {
                return;
            }

            if (config.ContainsKey("mcpServers") && config["mcpServers"].IsObject)
            {
                RemoveUnityMcpJsonEntries(config["mcpServers"]);
            }
            File.WriteAllText(mcpPath, config.ToJson());
        }

        private static void WriteCodexConfig(string projectRoot, string serverUrl, string clientToken)
        {
            var codexDir = Path.Combine(projectRoot, CodexConfigDirectoryName);
            Directory.CreateDirectory(codexDir);

            var codexPath = Path.Combine(codexDir, CodexConfigFileName);
            var existing = File.Exists(codexPath) ? File.ReadAllText(codexPath) : string.Empty;
            var withoutUnityMcp = RemoveUnityMcpConfig(existing).TrimEnd();

            var builder = new StringBuilder();
            if (!string.IsNullOrEmpty(withoutUnityMcp))
            {
                builder.Append(withoutUnityMcp);
                builder.AppendLine();
                builder.AppendLine();
            }

            builder.AppendLine(CodexManagedBlockStart);
            builder.AppendLine(CodexGeneratedComment);
            builder.AppendLine(CodexRegeneratedComment);
            builder.Append("[mcp_servers.");
            builder.Append(McpServerName);
            builder.AppendLine("]");
            builder.Append("url = ");
            builder.AppendLine(TomlString(serverUrl));
            builder.Append("http_headers = { Authorization = ");
            builder.Append(TomlString("Bearer " + clientToken));
            builder.AppendLine(" }");
            builder.AppendLine(CodexManagedBlockEnd);

            File.WriteAllText(codexPath, builder.ToString());
        }

        private static void RemoveCodexConfig(string projectRoot)
        {
            var codexPath = Path.Combine(projectRoot, CodexConfigDirectoryName, CodexConfigFileName);
            if (!File.Exists(codexPath))
            {
                return;
            }

            string withoutUnityMcp = RemoveUnityMcpConfig(File.ReadAllText(codexPath)).TrimEnd();
            File.WriteAllText(codexPath, string.IsNullOrEmpty(withoutUnityMcp)
                ? string.Empty
                : withoutUnityMcp + Environment.NewLine);
        }

        private static void WriteOpenCodeConfig(string projectRoot, string serverUrl, string clientToken)
        {
            var openCodeDir = Path.Combine(projectRoot, OpenCodeConfigDirectoryName);
            Directory.CreateDirectory(openCodeDir);

            var openCodePath = Path.Combine(openCodeDir, OpenCodeConfigFileName);
            JsonData config = ReadJsonObjectOrNew(openCodePath);
            if (config == null)
            {
                return;
            }

            config["$schema"] = OpenCodeSchema;
            JsonData servers = EnsureObject(config, "mcp");
            RemoveUnityMcpJsonEntries(servers);
            servers[McpServerName] = OpenCodeServerEntry(serverUrl, clientToken);
            File.WriteAllText(openCodePath, config.ToJson());
        }

        private static void RemoveOpenCodeConfig(string projectRoot)
        {
            var openCodePath = Path.Combine(projectRoot, OpenCodeConfigDirectoryName, OpenCodeConfigFileName);
            if (!File.Exists(openCodePath))
            {
                return;
            }

            JsonData config = ReadJsonObjectOrNew(openCodePath);
            if (config == null)
            {
                return;
            }

            if (config.ContainsKey("mcp") && config["mcp"].IsObject)
            {
                RemoveUnityMcpJsonEntries(config["mcp"]);
            }
            File.WriteAllText(openCodePath, config.ToJson());
        }

        private static JsonData OpenCodeServerEntry(string serverUrl, string clientToken)
        {
            var headers = new JsonData();
            headers["Authorization"] = "Bearer " + clientToken;

            var serverEntry = new JsonData();
            serverEntry["type"] = "remote";
            serverEntry["url"] = serverUrl;
            serverEntry["enabled"] = true;
            serverEntry["oauth"] = false;
            serverEntry["headers"] = headers;
            return serverEntry;
        }

        private static JsonData McpServerEntry(string serverUrl, string clientToken)
        {
            var headers = new JsonData();
            headers["Authorization"] = "Bearer " + clientToken;

            var serverEntry = new JsonData();
            serverEntry["type"] = "http";
            serverEntry["url"] = serverUrl;
            serverEntry["headers"] = headers;
            return serverEntry;
        }

        private static JsonData ReadJsonObjectOrNew(string path)
        {
            if (!File.Exists(path))
            {
                var result = new JsonData();
                result.SetJsonType(JsonType.Object);
                return result;
            }

            try
            {
                JsonData parsed = JsonMapper.ToObject(File.ReadAllText(path));
                return parsed != null && parsed.IsObject ? parsed : null;
            }
            catch (Exception)
            {
                return null;
            }
        }

        private static JsonData EnsureObject(JsonData parent, string key)
        {
            if (parent.ContainsKey(key) && parent[key] != null && parent[key].IsObject)
            {
                return parent[key];
            }

            var child = new JsonData();
            child.SetJsonType(JsonType.Object);
            parent[key] = child;
            return child;
        }

        private static void RemoveUnityMcpJsonEntries(JsonData servers)
        {
            if (servers.ContainsKey(McpServerName))
            {
                servers.Remove(McpServerName);
            }
            if (servers.ContainsKey(LegacyMcpServerName))
            {
                servers.Remove(LegacyMcpServerName);
            }
        }

        private static string RemoveUnityMcpConfig(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return string.Empty;
            }

            var lines = text.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
            var builder = new StringBuilder();
            var skipping = false;
            var skippingManagedBlock = false;

            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                if (trimmed == CodexManagedBlockStart || trimmed == LegacyCodexManagedBlockStart)
                {
                    skippingManagedBlock = true;
                    continue;
                }

                if (skippingManagedBlock)
                {
                    if (trimmed == CodexManagedBlockEnd || trimmed == LegacyCodexManagedBlockEnd)
                    {
                        skippingManagedBlock = false;
                    }
                    continue;
                }

                if (trimmed == CodexGeneratedComment || trimmed == CodexRegeneratedComment)
                {
                    continue;
                }

                if (IsUnityMcpHeader(trimmed))
                {
                    skipping = true;
                    continue;
                }

                if (skipping && IsTableHeader(trimmed) && !IsUnityMcpHeader(trimmed))
                {
                    skipping = false;
                }

                if (!skipping)
                {
                    builder.AppendLine(line);
                }
            }

            return builder.ToString();
        }

        private static bool IsUnityMcpHeader(string trimmedLine)
        {
            return IsMcpServerHeader(trimmedLine, McpServerName)
                || IsMcpServerHeader(trimmedLine, LegacyMcpServerName);
        }

        private static bool IsMcpServerHeader(string trimmedLine, string serverName)
        {
            return trimmedLine == "[mcp_servers." + serverName + "]"
                || trimmedLine.StartsWith("[mcp_servers." + serverName + ".", StringComparison.Ordinal);
        }

        private static bool IsTableHeader(string trimmedLine)
        {
            return trimmedLine.StartsWith("[", StringComparison.Ordinal)
                && trimmedLine.EndsWith("]", StringComparison.Ordinal);
        }

        private static string TomlString(string value)
        {
            var builder = new StringBuilder();
            builder.Append('"');
            foreach (var c in value ?? string.Empty)
            {
                switch (c)
                {
                    case '\\':
                        builder.Append("\\\\");
                        break;
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\b':
                        builder.Append("\\b");
                        break;
                    case '\t':
                        builder.Append("\\t");
                        break;
                    case '\n':
                        builder.Append("\\n");
                        break;
                    case '\f':
                        builder.Append("\\f");
                        break;
                    case '\r':
                        builder.Append("\\r");
                        break;
                    default:
                        if (char.IsControl(c))
                        {
                            builder.Append("\\u");
                            builder.Append(((int)c).ToString("x4"));
                        }
                        else
                        {
                            builder.Append(c);
                        }
                        break;
                }
            }
            builder.Append('"');
            return builder.ToString();
        }

        // chmod 0600 on unix. gorilla-style FileMode is not honored by Mono's
        // File API here, so we shell out to chmod; on Windows this is a no-op.
        private static void RestrictToOwner(string path)
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                return;
            }

            var psi = new System.Diagnostics.ProcessStartInfo("chmod", "600 \"" + path + "\"")
            {
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using (var proc = System.Diagnostics.Process.Start(psi))
            {
                proc.WaitForExit();
                if (proc.ExitCode != 0)
                {
                    throw new System.IO.IOException(
                        "chmod 600 failed on " + path + " (exit " + proc.ExitCode +
                        "); discovery file may be world-readable");
                }
            }
        }
    }
}
