using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using LitJson;
using VeryFS.UnityMCP.Editor.Commands;
using VeryFS.UnityMCP.Editor.Protocol;

namespace VeryFS.UnityMCP.Editor.Commands.AgentSkill
{
    internal sealed class AgentSkillGenerationInput
    {
        public AgentSkillGenerationInput(InstallAgentSkillOptions options, string projectRoot, string unityVersion)
        {
            Options = options;
            ProjectRoot = projectRoot;
            UnityVersion = unityVersion;
        }

        public InstallAgentSkillOptions Options { get; }
        public string ProjectRoot { get; }
        public string UnityVersion { get; }
    }

    internal sealed class AgentSkillGenerationResult
    {
        public AgentSkillGenerationResult(string content, int toolCount)
        {
            Content = content;
            ToolCount = toolCount;
        }

        public string Content { get; }
        public int ToolCount { get; }
    }

    internal interface IAgentSkillMarkdownGenerator
    {
        void ValidateRequestedTools(InstallAgentSkillOptions options, IReadOnlyList<RpcToolDescriptor> descriptors);
        AgentSkillGenerationResult Generate(string template, AgentSkillGenerationInput input,
            IReadOnlyList<RpcToolDescriptor> descriptors);
    }

    internal sealed class AgentSkillMarkdownGenerator : IAgentSkillMarkdownGenerator
    {
        private static readonly string[] StructuralTokens =
        {
            "{{TEST_ASSEMBLY_GUIDANCE}}",
            "{{UNITY_LAUNCH_GUIDANCE}}",
            "{{UNITY_EXECUTABLE_GUIDANCE}}",
            "{{TOOL_SUMMARY}}",
            "{{GENERATED_FROM}}"
        };

        private static readonly string[] ScalarTokens =
        {
            "{{SKILL_NAME}}",
            "{{PROJECT_PATH}}",
            "{{UNITY_VERSION}}"
        };

        private const string GeneratedFrom = "Generated by `install-agent-skill` from the bundled UnityMCP skill template "
            + "and current Unity runtime tool descriptors. To update this file, call `install-agent-skill` with `overwrite: true`.";

        public void ValidateRequestedTools(InstallAgentSkillOptions options, IReadOnlyList<RpcToolDescriptor> descriptors)
        {
            FilterAndSort(options, descriptors ?? new RpcToolDescriptor[0]);
        }

        public AgentSkillGenerationResult Generate(string template, AgentSkillGenerationInput input,
            IReadOnlyList<RpcToolDescriptor> descriptors)
        {
            ValidateTemplate(template);
            var tools = FilterAndSort(input.Options, descriptors ?? new RpcToolDescriptor[0]);
            string testAssemblyGuidance = BuildTestAssemblyGuidance(input.Options.TestAssemblies);
            string launchGuidance = BuildLaunchGuidance(input);
            string executableGuidance = BuildExecutableGuidance(input);

            string content = template.Replace("\r\n", "\n").Replace("\r", "\n")
                .Replace("{{SKILL_NAME}}", input.Options.Name)
                .Replace("{{PROJECT_PATH}}", EscapeMarkdown(input.ProjectRoot))
                .Replace("{{UNITY_VERSION}}", EscapeMarkdown(input.UnityVersion))
                .Replace("{{TEST_ASSEMBLY_GUIDANCE}}", testAssemblyGuidance)
                .Replace("{{UNITY_LAUNCH_GUIDANCE}}", launchGuidance)
                .Replace("{{UNITY_EXECUTABLE_GUIDANCE}}", executableGuidance)
                .Replace("{{TOOL_SUMMARY}}", BuildToolSummary(tools))
                .Replace("{{GENERATED_FROM}}", GeneratedFrom);

            if (content.Contains("{{"))
            {
                InvalidTemplate();
            }

            return new AgentSkillGenerationResult(content, tools.Count);
        }

        internal static string QuoteBash(string value)
            => "'" + value.Replace("'", "'\\''") + "'";

        internal static string QuotePowerShell(string value)
            => "'" + value.Replace("'", "''") + "'";

        private static void ValidateTemplate(string template)
        {
            if (template == null)
            {
                InvalidTemplate();
            }

            foreach (string token in StructuralTokens)
            {
                if (CountOccurrences(template, token) != 1)
                {
                    InvalidTemplate();
                }
            }

            foreach (string token in ScalarTokens)
            {
                if (CountOccurrences(template, token) < 1)
                {
                    InvalidTemplate();
                }
            }
        }

        private static int CountOccurrences(string value, string token)
        {
            int count = 0;
            int startIndex = 0;
            while ((startIndex = value.IndexOf(token, startIndex, StringComparison.Ordinal)) >= 0)
            {
                count++;
                startIndex += token.Length;
            }
            return count;
        }

        private static List<RpcToolDescriptor> FilterAndSort(InstallAgentSkillOptions options,
            IReadOnlyList<RpcToolDescriptor> descriptors)
        {
            var names = new HashSet<string>(descriptors.Select(descriptor => descriptor.Name), StringComparer.Ordinal);
            var unknown = options.IncludeTools.Concat(options.ExcludeTools)
                .Where(name => !names.Contains(name)).Distinct(StringComparer.Ordinal)
                .OrderBy(name => name, StringComparer.Ordinal).ToArray();
            if (unknown.Length > 0)
            {
                throw new AgentSkillOperationException(JsonRpcErrorCodes.InvalidParams, "unknown_tools",
                    string.Join(", ", unknown), unknown);
            }

            var included = new HashSet<string>(options.IncludeTools, StringComparer.Ordinal);
            var excluded = new HashSet<string>(options.ExcludeTools, StringComparer.Ordinal);
            return descriptors.Where(descriptor => included.Count == 0 || included.Contains(descriptor.Name))
                .Where(descriptor => !excluded.Contains(descriptor.Name))
                .OrderBy(descriptor => descriptor.Name, StringComparer.Ordinal).ToList();
        }

        private static string BuildTestAssemblyGuidance(IReadOnlyList<string> assemblies)
        {
            if (assemblies.Count == 0)
            {
                return "Determine the project test assembly names before calling `test-run`.";
            }

            return "Call `test-run` with: { \"assemblyNames\": ["
                + string.Join(", ", assemblies.Select(assembly => "\"" + EscapeJson(assembly) + "\"")) + "] }.";
        }

        private static string BuildLaunchGuidance(AgentSkillGenerationInput input)
        {
            if (string.IsNullOrEmpty(input.Options.UnityExecutable))
            {
                return "Locate the Unity Editor executable before starting it interactively.";
            }

            string executable = input.Options.UnityExecutable;
            string projectRoot = input.ProjectRoot;
            return "Bash: " + QuoteBash(executable) + " -projectPath " + QuoteBash(projectRoot)
                + " -logFile " + QuoteBash("/tmp/unity-editor.log") + " &\n"
                + "PowerShell: Start-Process -FilePath " + QuotePowerShell(executable) + " -ArgumentList "
                + "'-projectPath'," + QuotePowerShell(projectRoot) + ",'-logFile'," + QuotePowerShell("Temp\\unity-editor.log");
        }

        private static string BuildExecutableGuidance(AgentSkillGenerationInput input)
        {
            if (string.IsNullOrEmpty(input.Options.UnityExecutable))
            {
                return "Locate the Unity Editor executable before using batchmode.";
            }

            string executable = input.Options.UnityExecutable;
            string projectRoot = input.ProjectRoot;
            if (input.Options.TestAssemblies.Count == 0)
            {
                return "Bash: " + QuoteBash(executable) + " -batchmode -nographics -projectPath "
                    + QuoteBash(projectRoot) + " -logFile - -quit\n"
                    + "PowerShell: & " + QuotePowerShell(executable) + " -batchmode -nographics -projectPath "
                    + QuotePowerShell(projectRoot) + " -logFile - -quit";
            }

            string assemblies = string.Join(";", input.Options.TestAssemblies);
            return "Bash: " + QuoteBash(executable) + " -batchmode -nographics -projectPath "
                + QuoteBash(projectRoot) + " -runTests -testPlatform EditMode -assemblyNames " + QuoteBash(assemblies)
                + " -testResults " + QuoteBash("/tmp/editmode-results.xml") + " -logFile -\n"
                + "PowerShell: & " + QuotePowerShell(executable) + " -batchmode -nographics -projectPath "
                + QuotePowerShell(projectRoot) + " -runTests -testPlatform EditMode -assemblyNames " + QuotePowerShell(assemblies)
                + " -testResults " + QuotePowerShell("Temp\\editmode-results.xml") + " -logFile -";
        }

        private static string BuildToolSummary(IReadOnlyList<RpcToolDescriptor> descriptors)
        {
            var content = new StringBuilder("| Tool | Access | Completion | Purpose |\n|---|---|---|---|");
            foreach (var descriptor in descriptors)
            {
                content.Append("\n| `").Append(descriptor.Name).Append("` | ")
                    .Append(IsReadOnly(descriptor) ? "read-only" : "mutating").Append(" | ")
                    .Append(EscapeMarkdown(descriptor.Completion)).Append(" | ")
                    .Append(EscapeMarkdown(descriptor.Description)).Append(" |");
            }
            return content.ToString();
        }

        private static bool IsReadOnly(RpcToolDescriptor descriptor)
        {
            return descriptor.Annotations != null && descriptor.Annotations.IsObject
                && descriptor.Annotations.ContainsKey("readOnlyHint") && descriptor.Annotations["readOnlyHint"].IsBoolean
                && (bool)descriptor.Annotations["readOnlyHint"];
        }

        private static string EscapeMarkdown(string value)
        {
            return Regex.Replace(value ?? string.Empty, "\\s+", " ").Trim().Replace("|", "\\|");
        }

        private static string EscapeJson(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static void InvalidTemplate()
        {
            throw new AgentSkillOperationException(JsonRpcErrorCodes.InvalidEditorState, "skill_template_invalid",
                "The bundled agent skill template is invalid.");
        }
    }
}
