using System;
using System.Collections.Generic;
using System.IO;
using VeryFS.UnityMCP.Editor.Infrastructure;
using VeryFS.UnityMCP.Editor.Protocol;

namespace VeryFS.UnityMCP.Editor.Commands.AgentSkill
{
    internal interface IAgentSkillFileSystem
    {
        string GetFullPath(string path);
        bool TryGetAttributes(string path, out FileAttributes attributes);
        bool FileExists(string path);
        void CreateDirectory(string path);
        string ReadAllText(string path);
        void WriteAllText(string path, string content);
        void MoveFile(string source, string destination);
        void ReplaceFile(string source, string destination);
        void DeleteFile(string path);
    }

    internal sealed class SystemAgentSkillFileSystem : IAgentSkillFileSystem
    {
        public string GetFullPath(string path)
        {
            return Path.GetFullPath(path);
        }

        public bool TryGetAttributes(string path, out FileAttributes attributes)
        {
            try
            {
                attributes = File.GetAttributes(path);
                return true;
            }
            catch (FileNotFoundException)
            {
                attributes = default(FileAttributes);
                return false;
            }
            catch (DirectoryNotFoundException)
            {
                attributes = default(FileAttributes);
                return false;
            }
        }

        public bool FileExists(string path)
        {
            return File.Exists(path);
        }

        public void CreateDirectory(string path)
        {
            Directory.CreateDirectory(path);
        }

        public string ReadAllText(string path)
        {
            return File.ReadAllText(path);
        }

        public void WriteAllText(string path, string content)
        {
            File.WriteAllText(path, content);
        }

        public void MoveFile(string source, string destination)
        {
            File.Move(source, destination);
        }

        public void ReplaceFile(string source, string destination)
        {
            File.Replace(source, destination, null);
        }

        public void DeleteFile(string path)
        {
            File.Delete(path);
        }
    }

    internal sealed class AgentSkillPathResult
    {
        public AgentSkillPathResult(string key, string relativePath, string absolutePath)
        {
            Key = key;
            RelativePath = relativePath;
            AbsolutePath = absolutePath;
        }

        public string Key { get; }
        public string RelativePath { get; }
        public string AbsolutePath { get; }
    }

    internal sealed class AgentSkillWriteResult
    {
        public AgentSkillWriteResult(string relativePath, string absolutePath, bool overwritten)
            : this(new[] { new AgentSkillPathResult("agents", relativePath, absolutePath) }, overwritten)
        {
        }

        public AgentSkillWriteResult(IReadOnlyList<AgentSkillPathResult> paths, bool overwritten)
        {
            Paths = paths;
            RelativePath = paths.Count > 0 ? paths[0].RelativePath : string.Empty;
            AbsolutePath = paths.Count > 0 ? paths[0].AbsolutePath : string.Empty;
            Overwritten = overwritten;
        }

        public IReadOnlyList<AgentSkillPathResult> Paths { get; }
        public string RelativePath { get; }
        public string AbsolutePath { get; }
        public bool Overwritten { get; }
    }

    internal sealed class AgentSkillDeleteResult
    {
        public AgentSkillDeleteResult(
            IReadOnlyList<string> deletedRelativePaths,
            IReadOnlyList<string> preservedRelativePaths)
        {
            DeletedRelativePaths = deletedRelativePaths;
            PreservedRelativePaths = preservedRelativePaths;
        }

        public IReadOnlyList<string> DeletedRelativePaths { get; }
        public IReadOnlyList<string> PreservedRelativePaths { get; }
    }

    internal interface IAgentSkillFileStore
    {
        AgentSkillWriteResult Write(
            string projectRoot,
            string skillName,
            string content,
            bool overwrite,
            IReadOnlyList<string> clients);

        AgentSkillDeleteResult DeleteGenerated(string projectRoot, string skillName, IReadOnlyList<string> clients);
    }

    internal sealed class AgentSkillFileStore : IAgentSkillFileStore
    {
        private const string AgentsPathKey = "agents";
        private const string OpenCodePathKey = "opencode";
        private const string RelativeAgentsSkillPathPrefix = ".agents/skills/";
        private const string RelativeOpenCodeSkillPathPrefix = ".opencode/skills/";
        private const string SkillFileName = "SKILL.md";
        private const string GeneratedMarker =
            "Generated by `install-agent-skill` from the bundled UnityMCP skill template";

        private readonly IAgentSkillFileSystem fileSystem;
        private readonly IIdGenerator idGenerator;
        private readonly StringComparison pathComparison;

        public AgentSkillFileStore(
            IAgentSkillFileSystem fileSystem,
            IIdGenerator idGenerator,
            StringComparison pathComparison)
        {
            this.fileSystem = fileSystem;
            this.idGenerator = idGenerator;
            this.pathComparison = pathComparison;
        }

        public AgentSkillWriteResult Write(
            string projectRoot,
            string skillName,
            string content,
            bool overwrite,
            IReadOnlyList<string> clients)
        {
            var temporaryPaths = new List<string>();

            try
            {
                string rootPath = fileSystem.GetFullPath(projectRoot);
                IReadOnlyList<SkillTarget> targets = BuildTargets(rootPath, skillName, clients);
                bool overwritten = false;
                foreach (SkillTarget target in targets)
                {
                    ValidateTarget(rootPath, target);
                    target.Exists = fileSystem.FileExists(target.Path);
                    overwritten = overwritten || target.Exists;
                    if (target.Exists && !overwrite)
                    {
                        throw new AgentSkillOperationException(
                            JsonRpcErrorCodes.InvalidParams,
                            "skill_exists",
                            "The agent skill already exists.",
                            path: target.RelativePath);
                    }
                }

                var paths = new List<AgentSkillPathResult>();
                foreach (SkillTarget target in targets)
                {
                    fileSystem.CreateDirectory(target.DirectoryPath);
                    string temporaryPath = Path.Combine(
                        target.DirectoryPath,
                        "." + idGenerator.NewId("skill") + ".tmp");
                    temporaryPaths.Add(temporaryPath);
                    fileSystem.WriteAllText(temporaryPath, content);

                    if (target.Exists)
                    {
                        fileSystem.ReplaceFile(temporaryPath, target.Path);
                    }
                    else
                    {
                        fileSystem.MoveFile(temporaryPath, target.Path);
                    }

                    temporaryPaths.Remove(temporaryPath);
                    paths.Add(new AgentSkillPathResult(target.Key, target.RelativePath, target.Path));
                }

                return new AgentSkillWriteResult(paths, overwritten);
            }
            catch (AgentSkillOperationException)
            {
                DeleteTemporaryFiles(temporaryPaths);
                throw;
            }
            catch (Exception)
            {
                DeleteTemporaryFiles(temporaryPaths);
                throw new AgentSkillOperationException(
                    JsonRpcErrorCodes.InternalError,
                    "skill_write_failed",
                    "Failed to write the agent skill.");
            }
        }

        public AgentSkillDeleteResult DeleteGenerated(
            string projectRoot,
            string skillName,
            IReadOnlyList<string> clients)
        {
            try
            {
                string rootPath = fileSystem.GetFullPath(projectRoot);
                IReadOnlyList<SkillTarget> targets = BuildTargets(rootPath, skillName, clients);
                var deleted = new List<string>();
                var preserved = new List<string>();

                foreach (SkillTarget target in targets)
                {
                    ValidateTarget(rootPath, target);
                    if (!fileSystem.FileExists(target.Path))
                    {
                        continue;
                    }

                    string content = fileSystem.ReadAllText(target.Path);
                    if (content != null && content.Contains(GeneratedMarker))
                    {
                        fileSystem.DeleteFile(target.Path);
                        deleted.Add(target.RelativePath);
                    }
                    else
                    {
                        preserved.Add(target.RelativePath);
                    }
                }

                return new AgentSkillDeleteResult(deleted, preserved);
            }
            catch (AgentSkillOperationException)
            {
                throw;
            }
            catch (Exception)
            {
                throw new AgentSkillOperationException(
                    JsonRpcErrorCodes.InternalError,
                    "skill_delete_failed",
                    "Failed to delete the agent skill.");
            }
        }

        private IReadOnlyList<SkillTarget> BuildTargets(
            string rootPath,
            string skillName,
            IReadOnlyList<string> clients)
        {
            if (clients == null || clients.Count == 0)
            {
                throw new AgentSkillOperationException(
                    JsonRpcErrorCodes.InvalidParams,
                    "invalid_params",
                    "'clients' must contain at least one supported client.");
            }

            McpClientTarget clientTargets = McpClientTargets.FromNames(clients);
            if (clientTargets == McpClientTarget.None)
            {
                throw new AgentSkillOperationException(
                    JsonRpcErrorCodes.InvalidParams,
                    "invalid_params",
                    "'clients' must contain at least one supported client.");
            }

            var targets = new List<SkillTarget>();
            if ((clientTargets & (McpClientTarget.Claude | McpClientTarget.Codex)) != 0)
            {
                targets.Add(BuildTarget(
                    rootPath,
                    AgentsPathKey,
                    ".agents",
                    RelativeAgentsSkillPathPrefix + skillName + "/" + SkillFileName,
                    skillName));
            }
            if ((clientTargets & McpClientTarget.OpenCode) != 0)
            {
                targets.Add(BuildTarget(
                    rootPath,
                    OpenCodePathKey,
                    ".opencode",
                    RelativeOpenCodeSkillPathPrefix + skillName + "/" + SkillFileName,
                    skillName));
            }

            return targets;
        }

        private SkillTarget BuildTarget(
            string rootPath,
            string key,
            string clientDirectoryName,
            string relativePath,
            string skillName)
        {
            string clientDirectoryPath = fileSystem.GetFullPath(Path.Combine(rootPath, clientDirectoryName));
            string skillsDirectoryPath = fileSystem.GetFullPath(Path.Combine(clientDirectoryPath, "skills"));
            string directoryPath = fileSystem.GetFullPath(Path.Combine(skillsDirectoryPath, skillName));
            string path = fileSystem.GetFullPath(Path.Combine(directoryPath, SkillFileName));
            return new SkillTarget(key, relativePath, clientDirectoryPath, skillsDirectoryPath, directoryPath, path);
        }

        private void ValidateTarget(string rootPath, SkillTarget target)
        {
            EnsureContained(rootPath, target.ClientDirectoryPath);
            EnsureContained(rootPath, target.SkillsDirectoryPath);
            EnsureContained(target.SkillsDirectoryPath, target.DirectoryPath);
            EnsureContained(target.SkillsDirectoryPath, target.Path);
            RejectReparsePoints(
                target.ClientDirectoryPath,
                target.SkillsDirectoryPath,
                target.DirectoryPath,
                target.Path);
        }

        private void EnsureContained(string rootPath, string candidatePath)
        {
            string rootWithSeparator = rootPath.EndsWith(Path.DirectorySeparatorChar.ToString(), pathComparison)
                ? rootPath
                : rootPath + Path.DirectorySeparatorChar;
            if (!string.Equals(rootPath, candidatePath, pathComparison) &&
                !candidatePath.StartsWith(rootWithSeparator, pathComparison))
            {
                throw UnsafeSkillPath();
            }
        }

        private void RejectReparsePoints(params string[] paths)
        {
            foreach (string path in paths)
            {
                FileAttributes attributes;
                if (fileSystem.TryGetAttributes(path, out attributes) &&
                    (attributes & FileAttributes.ReparsePoint) != 0)
                {
                    throw UnsafeSkillPath();
                }
            }
        }

        private void DeleteTemporaryFiles(IReadOnlyList<string> temporaryPaths)
        {
            if (temporaryPaths == null)
            {
                return;
            }

            foreach (string temporaryPath in temporaryPaths)
            {
                try
                {
                    fileSystem.DeleteFile(temporaryPath);
                }
                catch (Exception)
                {
                }
            }
        }

        private static AgentSkillOperationException UnsafeSkillPath()
        {
            return new AgentSkillOperationException(
                JsonRpcErrorCodes.InvalidParams,
                "unsafe_skill_path",
                "The agent skill path is unsafe.");
        }

        private sealed class SkillTarget
        {
            public SkillTarget(
                string key,
                string relativePath,
                string clientDirectoryPath,
                string skillsDirectoryPath,
                string directoryPath,
                string path)
            {
                Key = key;
                RelativePath = relativePath;
                ClientDirectoryPath = clientDirectoryPath;
                SkillsDirectoryPath = skillsDirectoryPath;
                DirectoryPath = directoryPath;
                Path = path;
            }

            public string Key { get; }
            public string RelativePath { get; }
            public string ClientDirectoryPath { get; }
            public string SkillsDirectoryPath { get; }
            public string DirectoryPath { get; }
            public string Path { get; }
            public bool Exists { get; set; }
        }
    }
}
